name: Linux

on: [push]

jobs:
  plugin-tests:

    name: Plugin Tests
    runs-on: ubuntu-latest
    permissions:
      # Passing one of default ones.
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Sublime Text
        uses: 53v3n3d4/UnitTesting/actions/setup@7e4b8cc
        with:
          package-name: Zukan Icon Theme
          sublime-text-version: 4
      - name: Test with unittest
        uses: 53v3n3d4/UnitTesting/actions/run-tests@7e4b8cc
        with:
          coverage: true
          package-name: Zukan Icon Theme
